# Generated by Django 5.1.3 on 2024-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_etudiants/')),
                ('note_maths', models.FloatField()),
                ('note_physique', models.FloatField()),
                ('note_informatique', models.FloatField()),
                ('note_moyenne', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
